description: build libretro


inputs:
  token:
    description: github token
    required: false
    default: ''

  arch:
    description: system platform
    required: false
    default: x64


runs:
  using: composite

  steps:
    - uses: li1ht2ay-3es/gi1-ac2io3s@checkout-repo
      with:
        token: ${{ inputs.token }}
        branch: upstream
        auto: true


    - uses: li1ht2ay-3es/sa1eb2y@tools-install


    - uses: li1ht2ay-3es/gi1-ac2io3s@mingw-install
      with:
        arch: ${{ inputs.arch }}


    - uses: li1ht2ay-3es/gi1-ac2io3s@cache-read
      with:
        name: cache-${{ inputs.arch }}



    - shell: bash
      run: |
        merge () {
          echo "<<< ===  merging  $1  === >>>"
          git merge origin/$1
          echo ""
        }

        merge compiler-flags
        merge libretro-options

        merge crop-border
        merge fast-bootrom
        merge game-lag
        merge osd-message
        merge palette-bright
        merge sprite-limit
        merge sprite-priority
        merge video-overclock
        merge volume-level
        merge vram-blocking



    - working-directory: libretro
      shell: bash
      run: |
        make platform="win" CC="$MINGW_CC" CXX="$MINGW_CXX"



    - uses: li1ht2ay-3es/gi1-ac2io3s@cache-write
      with:
        name: cache-${{ inputs.arch }}


    - uses: actions/upload-artifact@main
      with:
        name: SameBoy_${{ inputs.arch }}
        path: build/bin
