on:
#  push:
  workflow_dispatch:


jobs:

  rgbds-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay-3es/gi1-ac2io3s@checkout-branch
        with:
          token: ${{ secrets.token }}
          auto: true


      - uses: li1ht2ay-3es/sa1eb2y@rgbds-ubuntu


      - run: |
          git add .
          git commit -m "rgbds - ubuntu"
          git push -f origin
